# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bank_pb2 as bank__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class BankAccountServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OpenAccount = channel.unary_unary(
        '/main.BankAccountService/OpenAccount',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=bank__pb2.AccountIdentifier.FromString,
        )
    self.WithdrawAccount = channel.unary_unary(
        '/main.BankAccountService/WithdrawAccount',
        request_serializer=bank__pb2.WithdrawAccountRequest.SerializeToString,
        response_deserializer=bank__pb2.AccountBalance.FromString,
        )
    self.DepositAccount = channel.unary_unary(
        '/main.BankAccountService/DepositAccount',
        request_serializer=bank__pb2.DepositAccountRequest.SerializeToString,
        response_deserializer=bank__pb2.AccountBalance.FromString,
        )
    self.GetBalance = channel.unary_unary(
        '/main.BankAccountService/GetBalance',
        request_serializer=bank__pb2.BalanceAccountRequest.SerializeToString,
        response_deserializer=bank__pb2.AccountBalance.FromString,
        )
    self.AddInterest = channel.unary_unary(
        '/main.BankAccountService/AddInterest',
        request_serializer=bank__pb2.AddInterestRequest.SerializeToString,
        response_deserializer=bank__pb2.AccountBalance.FromString,
        )


class BankAccountServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OpenAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def WithdrawAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DepositAccount(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBalance(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddInterest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BankAccountServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OpenAccount': grpc.unary_unary_rpc_method_handler(
          servicer.OpenAccount,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=bank__pb2.AccountIdentifier.SerializeToString,
      ),
      'WithdrawAccount': grpc.unary_unary_rpc_method_handler(
          servicer.WithdrawAccount,
          request_deserializer=bank__pb2.WithdrawAccountRequest.FromString,
          response_serializer=bank__pb2.AccountBalance.SerializeToString,
      ),
      'DepositAccount': grpc.unary_unary_rpc_method_handler(
          servicer.DepositAccount,
          request_deserializer=bank__pb2.DepositAccountRequest.FromString,
          response_serializer=bank__pb2.AccountBalance.SerializeToString,
      ),
      'GetBalance': grpc.unary_unary_rpc_method_handler(
          servicer.GetBalance,
          request_deserializer=bank__pb2.BalanceAccountRequest.FromString,
          response_serializer=bank__pb2.AccountBalance.SerializeToString,
      ),
      'AddInterest': grpc.unary_unary_rpc_method_handler(
          servicer.AddInterest,
          request_deserializer=bank__pb2.AddInterestRequest.FromString,
          response_serializer=bank__pb2.AccountBalance.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'main.BankAccountService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
