# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bank.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nbank.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"\x07\n\x05\x45mpty\"\'\n\x11\x41\x63\x63ountIdentifier\x12\x12\n\naccount_id\x18\x01 \x01(\t\";\n\x15\x44\x65positAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"<\n\x16WithdrawAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x02\"!\n\x0e\x41\x63\x63ountBalance\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x02\"+\n\x15\x42\x61lanceAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\">\n\x12\x41\x64\x64InterestRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x14\n\x0cinterestRate\x18\x02 \x01(\x02\x32\xe0\x02\n\x12\x42\x61nkAccountService\x12>\n\x0bOpenAccount\x12\x16.google.protobuf.Empty\x1a\x17.main.AccountIdentifier\x12\x45\n\x0fWithdrawAccount\x12\x1c.main.WithdrawAccountRequest\x1a\x14.main.AccountBalance\x12\x43\n\x0e\x44\x65positAccount\x12\x1b.main.DepositAccountRequest\x1a\x14.main.AccountBalance\x12?\n\nGetBalance\x12\x1b.main.BalanceAccountRequest\x1a\x14.main.AccountBalance\x12=\n\x0b\x41\x64\x64Interest\x12\x18.main.AddInterestRequest\x1a\x14.main.AccountBalanceb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='main.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=56,
)


_ACCOUNTIDENTIFIER = _descriptor.Descriptor(
  name='AccountIdentifier',
  full_name='main.AccountIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='main.AccountIdentifier.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=97,
)


_DEPOSITACCOUNTREQUEST = _descriptor.Descriptor(
  name='DepositAccountRequest',
  full_name='main.DepositAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='main.DepositAccountRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='main.DepositAccountRequest.amount', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=158,
)


_WITHDRAWACCOUNTREQUEST = _descriptor.Descriptor(
  name='WithdrawAccountRequest',
  full_name='main.WithdrawAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='main.WithdrawAccountRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='main.WithdrawAccountRequest.amount', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=220,
)


_ACCOUNTBALANCE = _descriptor.Descriptor(
  name='AccountBalance',
  full_name='main.AccountBalance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balance', full_name='main.AccountBalance.balance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=255,
)


_BALANCEACCOUNTREQUEST = _descriptor.Descriptor(
  name='BalanceAccountRequest',
  full_name='main.BalanceAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='main.BalanceAccountRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=300,
)


_ADDINTERESTREQUEST = _descriptor.Descriptor(
  name='AddInterestRequest',
  full_name='main.AddInterestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='main.AddInterestRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interestRate', full_name='main.AddInterestRequest.interestRate', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=364,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['AccountIdentifier'] = _ACCOUNTIDENTIFIER
DESCRIPTOR.message_types_by_name['DepositAccountRequest'] = _DEPOSITACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['WithdrawAccountRequest'] = _WITHDRAWACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['AccountBalance'] = _ACCOUNTBALANCE
DESCRIPTOR.message_types_by_name['BalanceAccountRequest'] = _BALANCEACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['AddInterestRequest'] = _ADDINTERESTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.Empty)
  ))
_sym_db.RegisterMessage(Empty)

AccountIdentifier = _reflection.GeneratedProtocolMessageType('AccountIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTIDENTIFIER,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.AccountIdentifier)
  ))
_sym_db.RegisterMessage(AccountIdentifier)

DepositAccountRequest = _reflection.GeneratedProtocolMessageType('DepositAccountRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEPOSITACCOUNTREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.DepositAccountRequest)
  ))
_sym_db.RegisterMessage(DepositAccountRequest)

WithdrawAccountRequest = _reflection.GeneratedProtocolMessageType('WithdrawAccountRequest', (_message.Message,), dict(
  DESCRIPTOR = _WITHDRAWACCOUNTREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.WithdrawAccountRequest)
  ))
_sym_db.RegisterMessage(WithdrawAccountRequest)

AccountBalance = _reflection.GeneratedProtocolMessageType('AccountBalance', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTBALANCE,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.AccountBalance)
  ))
_sym_db.RegisterMessage(AccountBalance)

BalanceAccountRequest = _reflection.GeneratedProtocolMessageType('BalanceAccountRequest', (_message.Message,), dict(
  DESCRIPTOR = _BALANCEACCOUNTREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.BalanceAccountRequest)
  ))
_sym_db.RegisterMessage(BalanceAccountRequest)

AddInterestRequest = _reflection.GeneratedProtocolMessageType('AddInterestRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDINTERESTREQUEST,
  __module__ = 'bank_pb2'
  # @@protoc_insertion_point(class_scope:main.AddInterestRequest)
  ))
_sym_db.RegisterMessage(AddInterestRequest)



_BANKACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='BankAccountService',
  full_name='main.BankAccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=367,
  serialized_end=719,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenAccount',
    full_name='main.BankAccountService.OpenAccount',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_ACCOUNTIDENTIFIER,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='WithdrawAccount',
    full_name='main.BankAccountService.WithdrawAccount',
    index=1,
    containing_service=None,
    input_type=_WITHDRAWACCOUNTREQUEST,
    output_type=_ACCOUNTBALANCE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DepositAccount',
    full_name='main.BankAccountService.DepositAccount',
    index=2,
    containing_service=None,
    input_type=_DEPOSITACCOUNTREQUEST,
    output_type=_ACCOUNTBALANCE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBalance',
    full_name='main.BankAccountService.GetBalance',
    index=3,
    containing_service=None,
    input_type=_BALANCEACCOUNTREQUEST,
    output_type=_ACCOUNTBALANCE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddInterest',
    full_name='main.BankAccountService.AddInterest',
    index=4,
    containing_service=None,
    input_type=_ADDINTERESTREQUEST,
    output_type=_ACCOUNTBALANCE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BANKACCOUNTSERVICE)

DESCRIPTOR.services_by_name['BankAccountService'] = _BANKACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
